/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as VcroPageRouteImport } from './routes/vcro.$page'
import { Route as VcroDepartmentsRouteImport } from './routes/vcro.departments'
import { Route as VcroGettingStartedRouteImport } from './routes/vcro.getting-started'
import { Route as VcroReportsRouteImport } from './routes/vcro.reports'
import { Route as VcroRiskometerRouteImport } from './routes/vcro.riskometer'
import { Route as VcroSettingsRouteImport } from './routes/vcro.settings'
import { Route as VcroWatchlistsRouteImport } from './routes/vcro.watchlists'
import { Route as VcroWeightageRouteImport } from './routes/vcro.weightage'
import { Route as VcroPeopleIndexRouteImport } from './routes/vcro.people.index'
import { Route as VcroPeopleIdRouteImport } from './routes/vcro.people.$id'
import { Route as VcroScorecardIdRouteImport } from './routes/vcro.scorecard.$id'
import { Route as VcroSignalsIndexRouteImport } from './routes/vcro.signals.index'
import { Route as VcroSignalsIdRouteImport } from './routes/vcro.signals.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroPageRoute = VcroPageRouteImport.update({
  id: '/vcro/$page',
  path: '/vcro/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroDepartmentsRoute = VcroDepartmentsRouteImport.update({
  id: '/vcro/departments',
  path: '/vcro/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroGettingStartedRoute = VcroGettingStartedRouteImport.update({
  id: '/vcro/getting-started',
  path: '/vcro/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroReportsRoute = VcroReportsRouteImport.update({
  id: '/vcro/reports',
  path: '/vcro/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroRiskometerRoute = VcroRiskometerRouteImport.update({
  id: '/vcro/riskometer',
  path: '/vcro/riskometer',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroSettingsRoute = VcroSettingsRouteImport.update({
  id: '/vcro/settings',
  path: '/vcro/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroWatchlistsRoute = VcroWatchlistsRouteImport.update({
  id: '/vcro/watchlists',
  path: '/vcro/watchlists',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroWeightageRoute = VcroWeightageRouteImport.update({
  id: '/vcro/weightage',
  path: '/vcro/weightage',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroPeopleIndexRoute = VcroPeopleIndexRouteImport.update({
  id: '/vcro/people/',
  path: '/vcro/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroPeopleIdRoute = VcroPeopleIdRouteImport.update({
  id: '/vcro/people/$id',
  path: '/vcro/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroScorecardIdRoute = VcroScorecardIdRouteImport.update({
  id: '/vcro/scorecard/$id',
  path: '/vcro/scorecard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroSignalsIndexRoute = VcroSignalsIndexRouteImport.update({
  id: '/vcro/signals/',
  path: '/vcro/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const VcroSignalsIdRoute = VcroSignalsIdRouteImport.update({
  id: '/vcro/signals/$id',
  path: '/vcro/signals/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/vcro/$page': typeof VcroPageRoute
  '/vcro/departments': typeof VcroDepartmentsRoute
  '/vcro/getting-started': typeof VcroGettingStartedRoute
  '/vcro/reports': typeof VcroReportsRoute
  '/vcro/riskometer': typeof VcroRiskometerRoute
  '/vcro/settings': typeof VcroSettingsRoute
  '/vcro/watchlists': typeof VcroWatchlistsRoute
  '/vcro/weightage': typeof VcroWeightageRoute
  '/vcro/people/$id': typeof VcroPeopleIdRoute
  '/vcro/scorecard/$id': typeof VcroScorecardIdRoute
  '/vcro/signals/$id': typeof VcroSignalsIdRoute
  '/vcro/people/': typeof VcroPeopleIndexRoute
  '/vcro/signals/': typeof VcroSignalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/vcro/$page': typeof VcroPageRoute
  '/vcro/departments': typeof VcroDepartmentsRoute
  '/vcro/getting-started': typeof VcroGettingStartedRoute
  '/vcro/reports': typeof VcroReportsRoute
  '/vcro/riskometer': typeof VcroRiskometerRoute
  '/vcro/settings': typeof VcroSettingsRoute
  '/vcro/watchlists': typeof VcroWatchlistsRoute
  '/vcro/weightage': typeof VcroWeightageRoute
  '/vcro/people/$id': typeof VcroPeopleIdRoute
  '/vcro/scorecard/$id': typeof VcroScorecardIdRoute
  '/vcro/signals/$id': typeof VcroSignalsIdRoute
  '/vcro/people': typeof VcroPeopleIndexRoute
  '/vcro/signals': typeof VcroSignalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/vcro/$page': typeof VcroPageRoute
  '/vcro/departments': typeof VcroDepartmentsRoute
  '/vcro/getting-started': typeof VcroGettingStartedRoute
  '/vcro/reports': typeof VcroReportsRoute
  '/vcro/riskometer': typeof VcroRiskometerRoute
  '/vcro/settings': typeof VcroSettingsRoute
  '/vcro/watchlists': typeof VcroWatchlistsRoute
  '/vcro/weightage': typeof VcroWeightageRoute
  '/vcro/people/$id': typeof VcroPeopleIdRoute
  '/vcro/scorecard/$id': typeof VcroScorecardIdRoute
  '/vcro/signals/$id': typeof VcroSignalsIdRoute
  '/vcro/people/': typeof VcroPeopleIndexRoute
  '/vcro/signals/': typeof VcroSignalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/vcro/$page'
    | '/vcro/departments'
    | '/vcro/getting-started'
    | '/vcro/reports'
    | '/vcro/riskometer'
    | '/vcro/settings'
    | '/vcro/watchlists'
    | '/vcro/weightage'
    | '/vcro/people/$id'
    | '/vcro/scorecard/$id'
    | '/vcro/signals/$id'
    | '/vcro/people/'
    | '/vcro/signals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/vcro/$page'
    | '/vcro/departments'
    | '/vcro/getting-started'
    | '/vcro/reports'
    | '/vcro/riskometer'
    | '/vcro/settings'
    | '/vcro/watchlists'
    | '/vcro/weightage'
    | '/vcro/people/$id'
    | '/vcro/scorecard/$id'
    | '/vcro/signals/$id'
    | '/vcro/people'
    | '/vcro/signals'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/vcro/$page'
    | '/vcro/departments'
    | '/vcro/getting-started'
    | '/vcro/reports'
    | '/vcro/riskometer'
    | '/vcro/settings'
    | '/vcro/watchlists'
    | '/vcro/weightage'
    | '/vcro/people/$id'
    | '/vcro/scorecard/$id'
    | '/vcro/signals/$id'
    | '/vcro/people/'
    | '/vcro/signals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  VcroPageRoute: typeof VcroPageRoute
  VcroDepartmentsRoute: typeof VcroDepartmentsRoute
  VcroGettingStartedRoute: typeof VcroGettingStartedRoute
  VcroReportsRoute: typeof VcroReportsRoute
  VcroRiskometerRoute: typeof VcroRiskometerRoute
  VcroSettingsRoute: typeof VcroSettingsRoute
  VcroWatchlistsRoute: typeof VcroWatchlistsRoute
  VcroWeightageRoute: typeof VcroWeightageRoute
  VcroPeopleIdRoute: typeof VcroPeopleIdRoute
  VcroScorecardIdRoute: typeof VcroScorecardIdRoute
  VcroSignalsIdRoute: typeof VcroSignalsIdRoute
  VcroPeopleIndexRoute: typeof VcroPeopleIndexRoute
  VcroSignalsIndexRoute: typeof VcroSignalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/$page': {
      id: '/vcro/$page'
      path: '/vcro/$page'
      fullPath: '/vcro/$page'
      preLoaderRoute: typeof VcroPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/departments': {
      id: '/vcro/departments'
      path: '/vcro/departments'
      fullPath: '/vcro/departments'
      preLoaderRoute: typeof VcroDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/getting-started': {
      id: '/vcro/getting-started'
      path: '/vcro/getting-started'
      fullPath: '/vcro/getting-started'
      preLoaderRoute: typeof VcroGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/reports': {
      id: '/vcro/reports'
      path: '/vcro/reports'
      fullPath: '/vcro/reports'
      preLoaderRoute: typeof VcroReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/riskometer': {
      id: '/vcro/riskometer'
      path: '/vcro/riskometer'
      fullPath: '/vcro/riskometer'
      preLoaderRoute: typeof VcroRiskometerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/settings': {
      id: '/vcro/settings'
      path: '/vcro/settings'
      fullPath: '/vcro/settings'
      preLoaderRoute: typeof VcroSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/watchlists': {
      id: '/vcro/watchlists'
      path: '/vcro/watchlists'
      fullPath: '/vcro/watchlists'
      preLoaderRoute: typeof VcroWatchlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/weightage': {
      id: '/vcro/weightage'
      path: '/vcro/weightage'
      fullPath: '/vcro/weightage'
      preLoaderRoute: typeof VcroWeightageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/people/': {
      id: '/vcro/people/'
      path: '/vcro/people'
      fullPath: '/vcro/people/'
      preLoaderRoute: typeof VcroPeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/people/$id': {
      id: '/vcro/people/$id'
      path: '/vcro/people/$id'
      fullPath: '/vcro/people/$id'
      preLoaderRoute: typeof VcroPeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/scorecard/$id': {
      id: '/vcro/scorecard/$id'
      path: '/vcro/scorecard/$id'
      fullPath: '/vcro/scorecard/$id'
      preLoaderRoute: typeof VcroScorecardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/signals/': {
      id: '/vcro/signals/'
      path: '/vcro/signals'
      fullPath: '/vcro/signals/'
      preLoaderRoute: typeof VcroSignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcro/signals/$id': {
      id: '/vcro/signals/$id'
      path: '/vcro/signals/$id'
      fullPath: '/vcro/signals/$id'
      preLoaderRoute: typeof VcroSignalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  VcroPageRoute: VcroPageRoute,
  VcroDepartmentsRoute: VcroDepartmentsRoute,
  VcroGettingStartedRoute: VcroGettingStartedRoute,
  VcroReportsRoute: VcroReportsRoute,
  VcroRiskometerRoute: VcroRiskometerRoute,
  VcroSettingsRoute: VcroSettingsRoute,
  VcroWatchlistsRoute: VcroWatchlistsRoute,
  VcroWeightageRoute: VcroWeightageRoute,
  VcroPeopleIdRoute: VcroPeopleIdRoute,
  VcroScorecardIdRoute: VcroScorecardIdRoute,
  VcroSignalsIdRoute: VcroSignalsIdRoute,
  VcroPeopleIndexRoute: VcroPeopleIndexRoute,
  VcroSignalsIndexRoute: VcroSignalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
